apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-deployment
  labels:
    app: piazza
spec:
  replicas: 5
  selector:
    matchLabels:
      app: piazza
  template:
    metadata:
      labels:
        app: piazza
    spec:
      containers:
      - name: minihi
        image: abatub01/piazza-app:1 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000